name: python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bootstrap-test:
    name: Bootstrap on Python ${{matrix.python-version}} @${{matrix.os-image}}
    strategy:
      matrix:
        os-image: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        bootstrap-args: ["--layout=module", "--layout=package", "--dev"]
    runs-on: ${{matrix.os-image}}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Run bootstrapper
        run: python3 ./bootstrap.py ${{matrix.bootstrap-args}} -d .test
