name: python-macos

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  style-check:
    name: Check PEP8 compliance on Python ${{matrix.python-version}}
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python-version}}
    - uses: dschep/install-pipenv-action@v1
    - name: Install development packages with pipenv
      run: ./bootstrap.py
    - name: Lint with pycodestyle
      run: |
        pipenv run pycodestyle

  test:
    name: Test on Python ${{matrix.python-version}} with PyTest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python-version}}
    - uses: dschep/install-pipenv-action@v1
    - name: Install development packages with pipenv
      run: ./bootstrap.py
    - name: Test with pytest
      run: |
        pipenv run pytest
