name: python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style-check:
    name: Check PEP8 and PEP484 compliance on Python ${{matrix.python-version}}
    runs-on: ${{matrix.os-image}}
    strategy:
      matrix:
        os-image: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - os-image: ubuntu-latest
            python-version: "3.6"
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install PipEnv
        run: pip install pipenv
      - name: Install development packages with pipenv
        run: ./bootstrap.py
      - name: Lint with flake8 and mypy
        run: |
          pipenv run flake8
          pipenv run mypy .

  test:
    name: Test on Python ${{matrix.python-version}} with PyTest
    runs-on: ${{matrix.os-image}}
    strategy:
      matrix:
        os-image: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - os-image: ubuntu-latest
            python-version: "3.6"
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install PipEnv
        run: pip install pipenv
      - name: Install development packages with pipenv
        run: ./bootstrap.py
      - name: Test with pytest
        run: |
          pipenv run pytest
